/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Features: typeof import('./components/Features.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Reviews: typeof import('./components/Reviews.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Services: typeof import('./components/Services.vue')['default']
    Testimonials: typeof import('./components/Testimonials.vue')['default']
    Trust: typeof import('./components/Trust.vue')['default']
  }
}
